export const INIT_START = "INIT_START";
export const INIT_SUCCESS = "INIT_SUCCESS";
export const INIT_FAILURE = "INIT_FAILURE";
export const MOVE_PLAYER_START = "MOVE_PLAYER_START";
export const MOVE_PLAYER_SUCCESS = "MOVE_PLAYER_SUCCESS";
export const MOVE_PLAYER_FAILURE = "MOVE_PLAYER_FAILURE";
